# Generated by Django 4.2.4 on 2023-08-28 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone_no', models.IntegerField(null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('tiffin', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('custmer_id', models.BigAutoField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('phone_no', models.IntegerField(null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('tiffin', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='yesno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(default=0, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice1.main_register')),
            ],
        ),
    ]
